import type { MachineLayer } from "@/components/KernelScene";
export type LayerNote = { name: string; label: string; description: string };
export type LabDetail = { figure: string; layers: Record<MachineLayer, LayerNote>; observer?: string; fixture?: string; exercise: string; cleanup?: string };
const layer = (name: string, label: string, description: string): LayerNote => ({ name, label, description });
export const labDetails: Record<string, LabDetail> = {
  "01": { figure: "PROCESS LINEAGE", layers: {
    process: layer("Process lineage", "01 / THE ATTEMPT", "Each branch represents a possible execution path. A process snapshot may miss a short-lived exec attempt; the diagram does not claim to reconstruct an observed parent-child tree."),
    kernel: layer("Exec boundary", "02 / THE HOOK", "sys_enter_execve records an attempt before its result is known. Preserve the event timestamp and host identity rather than treating a command name as a stable key."),
    transport: layer("Event record", "03 / THE EVIDENCE", "The ring buffer carries bounded event records to userspace. Received events illuminate this collection path; this model is not live process topology.") }, exercise: "Compare an exec event with a later process snapshot. Explain why a missing process does not invalidate the earlier attempt." },
  "02": { figure: "FILE ACCESS / ENTRY + EXIT", layers: {
    process: layer("Path + context", "01 / THE REQUEST", "The pathname and dirfd belong to an attempted open. A relative path needs process filesystem context before it can be resolved."),
    kernel: layer("Entry ↔ exit", "02 / THE CORRELATION", "Match openat entry and exit by thread ID. The two gates in this model represent that correlation, not two independent successful opens."),
    transport: layer("Return evidence", "03 / THE RESULT", "A nonnegative return can be a file descriptor; a negative return identifies an error. Neither reveals why the application selected the path.") }, exercise: "Find one pathname and its correlated return. Separate an attempted open from a successful file descriptor." },
  "03": { figure: "SOCKET / ATTEMPTED CROSSING", layers: {
    process: layer("Client → destination", "01 / THE ATTEMPT", "A client targets an address and port. The separated endpoints represent a requested connection, not proof that a link was established."),
    kernel: layer("Connect boundary", "02 / ENTRY + EXIT", "Correlate blocking connect entry and return to recover destination, latency and errno. An EINPROGRESS return needs a later readiness or socket-state signal."),
    transport: layer("Errno + interval", "03 / THE EVIDENCE", "Compare the fixture's available listener with its closed destination. The result describes this attempt, not the remote service's general health.") }, observer: "incident-lab run 03 --duration 10 --json", fixture: "cd /opt/incident-lab\n./target/release/connect-fixture", exercise: "Repeat with --pid <host-pid>. Compare the successful loopback connection with the retry after the listener closes.", cleanup: "The fixture closes its ephemeral listener automatically." },
  "04": { figure: "RESOLVER / MEASURED INTERVAL", layers: {
    process: layer("Resolver wrapper", "01 / THE CALL", "The target is the exported resolve_backend function. Fixture delay is intentional and must not be described as naturally occurring DNS latency."),
    kernel: layer("Entry → return", "02 / THE INTERVAL", "A uprobe and uretprobe bracket this wrapper. The three interval bars illustrate comparison, not recorded timing values."),
    transport: layer("Duration record", "03 / THE LIMIT", "latency_us measures time in the wrapper. It does not separate libc, caches, NSS, network or DNS-server time without additional probes.") }, observer: "sudo env INCIDENT_DNS_FIXTURE=/opt/incident-lab/target/release/dns-fixture incident-lab run 04 --duration 10 --json", fixture: "cd /opt/incident-lab\n./target/release/dns-fixture localhost 0\n./target/release/dns-fixture localhost 500", exercise: "Try 10, 100 and 500 ms fixture delays. Compare latency_us and state which delay you intentionally introduced.", cleanup: "The probes detach when the observer exits." },
  "05": { figure: "TCP / REPEATED ATTEMPTS", layers: {
    process: layer("Flow endpoints", "01 / THE SYMPTOM", "The fixture creates a short, controlled loss window on the disposable VM's loopback interface. The parallel paths represent repeated attempts, not live packets."),
    kernel: layer("Retransmit path", "02 / THE TRACEPOINT", "tcp_retransmit_skb reports that the kernel entered its retransmission path for a flow. The tracepoint's field offsets depend on the accepted kernel format."),
    transport: layer("Flow summary", "03 / THE COUNTS", "Raw events, per-flow totals and count buckets describe retransmission activity. They do not distinguish loss, reordering, receiver delay or congestion by themselves.") }, observer: "incident-lab run 05 --duration 15 --json", fixture: "cd /opt/incident-lab\nsudo ./scripts/run-retransmit-fixture.sh", exercise: "Run only in the disposable lab VM. Repeat without the netem fixture and compare event counts over the same duration.", cleanup: "The fixture removes only the qdisc it created. Verify cleanup with: tc qdisc show dev lo" },
  "06": { figure: "NAMESPACE / NESTED IDENTITIES", layers: {
    process: layer("Namespace frame", "01 / THE LOCAL VIEW", "Nested frames represent different PID views of the same process. The namespace-visible PID may be 1 while the host sees a different number."),
    kernel: layer("Host identity", "02 / THE KERNEL VIEW", "The event contains host PID and cgroup ID. The observer's --pid filter always accepts the host PID, not the namespace-visible value."),
    transport: layer("NSpid enrichment", "03 / THE CORRELATION", "Userspace reads /proc/<host-pid>/status while the process lives. That enrichment can race with exit; a cgroup ID alone does not name a container.") }, observer: "incident-lab run 06 --duration 12 --json", fixture: "cd /opt/incident-lab\nsudo unshare --fork --pid --mount-proc ./target/release/namespace-fixture", exercise: "Inspect the process from the host and namespace while it is alive. Explain which PID belongs in the observer filter.", cleanup: "The namespace is torn down when the fixture exits." },
  "07": { figure: "VERIFIER / PROGRAM PATH", layers: {
    process: layer("Program path", "01 / THE OBJECT", "The branching instruction path represents candidate program control flow. It is explanatory geometry, not the disassembly or verifier log of a run."),
    kernel: layer("Verifier gate", "02 / BEFORE ATTACH", "Distinguish a load rejection from an attached program that received no events. Preserve the complete verifier diagnostic and target kernel context."),
    transport: layer("Compatibility", "03 / THE RECEIPT", "An observed event establishes that this object loaded and attached here. CO-RE and BTF do not guarantee identical verifier behaviour across kernels.") }, exercise: "Compare load diagnostics and event output. Describe what a second kernel would need to prove before adding it to a compatibility matrix." },
};
