import { beforeEach, describe, expect, it } from 'vitest';
import { curricula, rubric } from './curriculum';
import { labs } from './labs';
import { deleteLearningRecord, explanationComplete, learningStorageKey, migrateLegacy, newLearningRecord, parseLearningRecords, parseRunnerEvent, readLearningRecord, saveLearningRecord } from './learning';
beforeEach(()=>localStorage.clear());
describe('curriculum coverage',()=>{it('authors readiness, alternatives, progressive hints, concepts and written transfer for every lab',()=>{for(const lab of labs){const c=curricula[lab.id];expect(c.hypotheses).toHaveLength(3);expect(c.hints).toHaveLength(3);expect(c.concepts.length).toBeGreaterThanOrEqual(3);expect(c.readiness.options[c.readiness.answer]).toBeTruthy();expect(c.transfer.length).toBeGreaterThan(80);expect(c.recall.length).toBeGreaterThan(60);}expect(rubric).toHaveLength(5);});});
describe('durable local learning records',()=>{
 it('preserves legacy verbatim without inheriting completion or a correctness claim',()=>{const legacy={labId:'01',phase:'complete',prediction:'original',unknownExtra:{keep:true}};localStorage.setItem('incident-lab:notebooks:v1',JSON.stringify({'01':legacy}));const n=readLearningRecord('01')!;expect(n.legacy).toEqual(legacy);expect(n.phase).toBe('readiness');saveLearningRecord(n);expect(JSON.parse(localStorage.getItem('incident-lab:notebooks:v1')!)['01']).toEqual(legacy);expect(readLearningRecord('01')?.legacy).toEqual(legacy);});
 it('retains all revisions and assistance history',()=>{const n=newLearningRecord('02');n.attempts=[{stage:'prediction',at:'2026-09-09',value:'first',assisted:false},{stage:'prediction',at:'2026-09-10',value:'revision',assisted:true}];n.hints=[{index:0,phase:'predict',at:'2026-09-10'}];expect(saveLearningRecord(n)).toBe(true);expect(readLearningRecord('02')?.attempts).toEqual(n.attempts);expect(readLearningRecord('02')?.hints).toEqual(n.hints);});
 it('normalizes interrupted running sessions and rejects malformed persisted entries',()=>{const n=newLearningRecord('01');n.runState='running';saveLearningRecord(n);expect(readLearningRecord('01')?.runState).toBe('interrupted');expect(parseLearningRecords(JSON.stringify({'01':{...n,reasoning:null}}))).toEqual({});expect(parseLearningRecords('{oops')).toEqual({});expect(migrateLegacy('null')).toEqual({});});
 it('delete removes migrated source so records do not reappear',()=>{localStorage.setItem('incident-lab:notebooks:v1',JSON.stringify({'01':{labId:'01'}}));expect(deleteLearningRecord('01')).toBe(true);expect(readLearningRecord('01')).toBeUndefined();expect(localStorage.getItem(learningStorageKey)).toBe('{}');});
 it('checks completeness rather than semantic correctness and rejects dangling citations',()=>{const n=newLearningRecord('01');n.reasoning={claim:'wrong',mechanism:'wrong',unknown:'wrong',nextStep:'wrong'};n.citations=[2];expect(explanationComplete(n)).toBe(false);n.events=[{sequence:2,kind:'observation',timestamp:1,data:'raw'}];expect(explanationComplete(n)).toBe(true);});
});
it('validates stream records without trusting payload status text',()=>{expect(parseRunnerEvent('{oops')).toBeNull();expect(parseRunnerEvent(JSON.stringify({sequence:-1,timestamp:1,kind:'observation',data:'x'}))).toBeNull();expect(parseRunnerEvent(JSON.stringify({sequence:1,timestamp:1,kind:'terminal',data:'not completed'}))?.data).toBe('not completed');});
