import {beforeEach,expect,it,vi} from 'vitest';
import {POST} from './route';
const input={consent:true,labId:'02',claim:'An open failed',reasoning:'Return evidence',unknown:'Intent',nextStep:'Check context',evidence:[],hintsUsed:0};
function request(body:unknown,origin='http://localhost'){return new Request('http://localhost/api/tutor',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});}
beforeEach(()=>{vi.stubGlobal('fetch',vi.fn());vi.stubEnv('GROQ_API_KEY','');vi.stubEnv('GROQ_MODEL','');});
it('does not send reasoning without consent or same origin',async()=>{expect((await POST(request({...input,consent:false}))).status).toBe(400);expect((await POST(request(input,'https://other.example'))).status).toBe(403);expect(fetch).not.toHaveBeenCalled();});
it('fails honestly when not configured',async()=>{const response=await POST(request(input));expect(response.status).toBe(503);expect((await response.json()).message).toMatch(/no AI assessment/);expect(fetch).not.toHaveBeenCalled();});
it('bounds fields and evidence before provider use',async()=>{expect((await POST(request({...input,evidence:[{sequence:1,data:5}]}))).status).toBe(400);expect((await POST(request({...input,claim:'x'.repeat(4001)}))).status).toBe(400);expect(fetch).not.toHaveBeenCalled();});
it('uses Groq without tools and refuses incomplete output',async()=>{vi.stubEnv('GROQ_API_KEY','test-key');vi.stubEnv('GROQ_MODEL','configured-model');vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({choices:[{finish_reason:'length',message:{content:'partial'}}]})} as Response);expect((await POST(request(input))).status).toBe(502);expect(vi.mocked(fetch).mock.calls[0][0]).toBe('https://api.groq.com/openai/v1/chat/completions');const body=JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string);expect(body.tools).toBeUndefined();expect(body.reasoning_effort).toBe('none');expect(body.messages[0].content).toMatch(/no tools or execution authority/);});
it('returns bounded formative Groq feedback',async()=>{vi.stubEnv('GROQ_API_KEY','test-key');vi.stubEnv('GROQ_MODEL','configured-model');vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:'Which record distinguishes failure from fallback?'}}]})} as Response);const response=await POST(request(input));expect(response.status).toBe(200);expect(await response.json()).toMatchObject({provider:'Groq',model:'configured-model',assessment:'formative-only'});});
