"use client";
import { useEffect, useRef, useState } from "react";
import type { Lab } from "@/lib/labs";
import { labDetails } from "@/lib/lab-details";
import { curricula, rubric } from "@/lib/curriculum";
import { newLearningRecord, readLearningRecord, saveLearningRecord, downloadLearningRecord, explanationComplete, parseRunnerEvent, type LearningRecord, type LearningPhase } from "@/lib/learning";
import { EvidenceDiagram } from "./EvidenceDiagram";
const phases: LearningPhase[] = ["readiness","predict","observe","explain","transfer","review"];
export function InvestigationFlow({lab}:{lab:Lab}) {return <Flow key={lab.id} lab={lab}/>;}
function Flow({lab}:{lab:Lab}) {
  const c=curricula[lab.id]; const detail=labDetails[lab.id];
  const [record,setRecord]=useState<LearningRecord>(()=>readLearningRecord(lab.id)??newLearningRecord(lab.id));
  const [error,setError]=useState(""); const [saveError,setSaveError]=useState(false); const [local,setLocal]=useState(""); const [selected,setSelected]=useState<number>();
  const [tutorPhase,setTutorPhase]=useState<LearningPhase>();
  const [consent,setConsent]=useState(false); const [includeEvidence,setIncludeEvidence]=useState(false); const [tutor,setTutor]=useState(""); const [tutorBusy,setTutorBusy]=useState(false); const [scenarios,setScenarios]=useState<string[]>([]);
  const generation=useRef(0); const stream=useRef<EventSource|null>(null); const abort=useRef<AbortController|null>(null); const mounted=useRef(true); const tutorAbort=useRef<AbortController|null>(null);
  const update=(fn:(r:LearningRecord)=>LearningRecord)=>setRecord(r=>({...fn(r),updatedAt:new Date().toISOString()}));
  useEffect(()=>{const ok=saveLearningRecord(record);queueMicrotask(()=>setSaveError(!ok));},[record]);
  useEffect(()=>{mounted.current=true;const activeGeneration=generation;return()=>{mounted.current=false;activeGeneration.current++;stream.current?.close();abort.current?.abort();tutorAbort.current?.abort();};},[]);
  useEffect(()=>{if(lab.id!=="02")return;const ctrl=new AbortController();fetch('/api/runner/v1/capabilities',{signal:ctrl.signal}).then(r=>r.ok?r.json():null).then(v=>{if(!ctrl.signal.aborted&&Array.isArray(v?.fileScenarios))setScenarios(v.fileScenarios.filter((s:unknown)=>typeof s==='string'));}).catch(()=>{});return()=>ctrl.abort();},[lab.id]);
  function assistance(kind:string) {update(r=>({...r,assistance:[...(r.assistance??[]),{phase:r.phase,kind,at:new Date().toISOString()}],transfer:{...r.transfer,assisted:r.transfer.assisted||r.phase==='transfer'},recall:{...r.recall,assisted:r.recall.assisted||r.phase==='review'},attempts:r.phase==='transfer'&&r.transfer.answer.trim()&&!r.transfer.assisted?[...r.attempts,{stage:'transfer-before-help',value:r.transfer.answer,at:new Date().toISOString(),assisted:false}]:r.attempts}));}
  function attempt(stage:string,value:unknown,next?:LearningPhase) {update(r=>({...r,phase:next??r.phase,attempts:[...r.attempts,{stage,value,at:new Date().toISOString(),assisted:stage==='transfer'?r.transfer.assisted:r.hints.length>0||(r.assistance??[]).length>0}]}));}
  function hint(){assistance('authored hint');const index=record.hints.length%c.hints.length;update(r=>({...r,hints:[...r.hints,{index,phase:r.phase,at:new Date().toISOString()}],transfer:{...r.transfer,assisted:r.transfer.assisted||r.phase==='transfer'}}));}
  async function run(scenario?:'fallback'|'relative') {
    const gen=++generation.current; stream.current?.close();abort.current?.abort();const ctrl=new AbortController();abort.current=ctrl;setError("");setSelected(undefined);
    const target=scenario==='fallback'?'transferEvents':scenario==='relative'?'recallEvents':'events';
    const stateKey=scenario==='fallback'?'transferRunState':scenario==='relative'?'recallRunState':'runState';
    const sessionKey=scenario==='fallback'?'transferSessionId':scenario==='relative'?'recallSessionId':'sessionId';
    update(r=>({...r,runHistory:(r[target]?.length||r[sessionKey])?[...(r.runHistory??[]),{scenario:scenario??'baseline',sessionId:r[sessionKey],status:r[stateKey]??'unknown',events:r[target]??[],at:new Date().toISOString()}]:r.runHistory,[target]:[],[sessionKey]:undefined,...(scenario?{}:{citations:[]}),[stateKey]:'connecting'}));
    try {
      const response=await fetch('/api/runner/v1/sessions',{method:'POST',headers:{'content-type':'application/json'},signal:ctrl.signal,body:JSON.stringify({labId:lab.id,...(scenario?{scenarioId:scenario}:{})})});
      const body=await response.json();if(gen!==generation.current||ctrl.signal.aborted)return;
      if(!response.ok)throw new Error(body.message??'Runner unavailable. No observation is claimed.');
      if(typeof body.id!=='string'||!/^[a-zA-Z0-9-]+$/.test(body.id))throw new Error('Runner returned an invalid session identifier.');
      const sessionId=body.id; update(r=>({...r,[sessionKey]:sessionId,[stateKey]:'running'}));
      const source=new EventSource(`/api/runner/v1/sessions/${sessionId}/events`);stream.current=source;let terminal=false;
      const receive=async(message:MessageEvent)=>{
        if(gen!==generation.current||terminal)return;const event=parseRunnerEvent(message.data);
        if(!event){setError('An invalid stream record was ignored; it is not evidence.');return;}
        update(r=>({...r,[target]:(r[target]??[]).some(e=>e.sequence===event.sequence)?r[target]:[...(r[target]??[]),event].sort((a,b)=>a.sequence-b.sequence)}));
        if(event.kind==='terminal') {terminal=true;source.close();try {const statusResponse=await fetch(`/api/runner/v1/sessions/${sessionId}`,{signal:ctrl.signal});const status=await statusResponse.json();if(gen!==generation.current||ctrl.signal.aborted)return;if(!statusResponse.ok||status.status!=='completed')throw new Error('The session did not report completed status. Retained output may be partial.');update(r=>({...r,[stateKey]:'completed'}));}catch(e){if(gen!==generation.current||ctrl.signal.aborted)return;update(r=>({...r,[stateKey]:'failed'}));setError(e instanceof Error?e.message:'Session verification failed.');}}
      };
      ['status','observation','diagnostic','terminal'].forEach(name=>source.addEventListener(name,receive));
      source.onerror=()=>{if(gen!==generation.current||terminal)return;source.close();terminal=true;update(r=>({...r,[stateKey]:'interrupted'}));setError('Evidence stream interrupted. Saved events are partial; retry explicitly.');};
    }catch(e){if(gen!==generation.current||ctrl.signal.aborted)return;update(r=>({...r,[stateKey]:'failed'}));setError(e instanceof Error?e.message:'Runner unavailable.');}
  }
  const tutorPayload={consent:true,labId:lab.id,claim:record.reasoning.claim,reasoning:record.reasoning.mechanism,unknown:record.reasoning.unknown,nextStep:record.reasoning.nextStep,evidence:includeEvidence?record.events.filter(e=>record.citations.includes(e.sequence)).map(({sequence,data})=>({sequence,data})):[],hintsUsed:record.hints.length};
  async function requestTutor(){if(!consent||tutorBusy)return;const ctrl=new AbortController();tutorAbort.current=ctrl;setTutorBusy(true);setTutorPhase(record.phase);setTutor('');assistance('tutor request');if(record.phase==='transfer')update(r=>({...r,transfer:{...r.transfer,assisted:true}}));try{const response=await fetch('/api/tutor',{method:'POST',signal:ctrl.signal,headers:{'content-type':'application/json'},body:JSON.stringify(tutorPayload)});const body=await response.json();if(!response.ok)throw new Error(body.message??'Tutor unavailable. Use the authored guidance below.');if(mounted.current){update(r=>({...r,attempts:[...r.attempts,{stage:'tutor-feedback',value:body,at:new Date().toISOString(),assisted:true}]}));setTutor(typeof body.feedback==='string'?body.feedback:typeof body.message==='string'?body.message:JSON.stringify(body));}}catch(e){if(!ctrl.signal.aborted&&mounted.current)setTutor(e instanceof Error?e.message:'Tutor unavailable.');}finally{if(mounted.current)setTutorBusy(false);}}
  const evidence=record.events.filter(e=>e.kind==='observation'||e.kind==='diagnostic'); const busy=[record.runState,record.transferRunState,record.recallRunState].some(s=>['connecting','running','queued'].includes(s??''));
  const field=(key:keyof LearningRecord['reasoning'],label:string)=><label className="learn-field" key={key}>{label}<textarea value={record.reasoning[key]} onChange={e=>update(r=>({...r,reasoning:{...r.reasoning,[key]:e.target.value}}))}/></label>;
  return <section className="learn-flow" aria-label="Diagnostic learning investigation">
    <nav className="learn-steps" aria-label="Learning stages">{phases.map((p,i)=><span key={p} className={record.phase===p?'learn-step active':'learn-step'} aria-current={record.phase===p?'step':undefined}>{i+1}. {p}</span>)}</nav>
    <p className="learn-storage">Saved on this device · Assistance is recorded · Reviews stay separate from completion.</p>
    {saveError&&<p role="alert">Browser storage is unavailable. Export your record before leaving.</p>}
    {record.legacy!==undefined&&<details className="learn-legacy" key={record.phase} onToggle={e=>{if(e.currentTarget.open)assistance('legacy notebook reference');}}><summary>Original legacy notebook (preserved, not reassessed)</summary><pre>{JSON.stringify(record.legacy,null,2)}</pre></details>}
    {record.phase==='readiness'&&<div className="learn-panel"><p className="learn-kicker">Readiness · one concrete prerequisite</p><h2>{c.readiness.question}</h2><fieldset><legend>Select the supported statement</legend>{c.readiness.options.map((option,i)=><label key={option}><input type="radio" name="readiness" checked={record.readiness.answer===i} onChange={()=>update(r=>({...r,readiness:{answer:i,checked:false,correct:false}}))}/>{option}</label>)}</fieldset><button disabled={record.readiness.answer===null} onClick={()=>{const correct=record.readiness.answer===c.readiness.answer;update(r=>({...r,readiness:{...r.readiness,checked:true,correct},attempts:[...r.attempts,{stage:'readiness',value:r.readiness.answer,at:new Date().toISOString(),assisted:r.attempts.some(a=>a.stage==='readiness')}]}));}}>Check readiness</button>{record.readiness.checked&&<p role="status">{record.readiness.correct?'Ready. ': 'Try again after this explanation. '}{c.readiness.remediation}</p>}{record.readiness.correct&&<button onClick={()=>update(r=>({...r,phase:'predict'}))}>Build a prediction</button>}</div>}
    {record.phase==='predict'&&<div className="learn-panel"><p className="learn-kicker">Predict before observing</p><h2>Which explanation would you test first?</h2><fieldset><legend>Three competing hypotheses</legend>{c.hypotheses.map((h,i)=><label key={h}><input type="radio" name="hypothesis" checked={record.prediction.hypothesis===i} onChange={()=>update(r=>({...r,prediction:{...r.prediction,hypothesis:i}}))}/>{h}</label>)}</fieldset><label className="learn-field">What evidence would distinguish your hypothesis from the alternatives? Include an expected result and a result that would change your mind.<textarea value={record.prediction.evidence} onChange={e=>update(r=>({...r,prediction:{...r.prediction,evidence:e.target.value}}))}/></label><button disabled={record.prediction.hypothesis===null||!record.prediction.evidence.trim()} onClick={()=>attempt('prediction',record.prediction,'observe')}>Preserve prediction and investigate</button></div>}
    {record.phase==='observe'&&<div className="learn-panel"><p className="learn-kicker">Observe · {record.source==='hosted'?'fixed hosted experiment':'local VM experiment'}</p><h2>Collect discriminating evidence</h2>{lab.id==='07'&&<div><p>Compare successful hosted attachment with an intentional verifier rejection from the source repository in your local Linux VM. Each source retains a separate run history.</p><button disabled={busy} onClick={()=>update(r=>({...r,source:r.source==='hosted'?'local':'hosted',runHistory:r.events.length?[...(r.runHistory??[]),{scenario:r.source==='hosted'?'baseline':'local-verifier-rejection-unverified',sessionId:r.sessionId,status:r.runState,events:r.events,at:new Date().toISOString()}]:r.runHistory,events:[],citations:[],sessionId:undefined,runState:'idle'}))}>{record.source==='hosted'?'Investigate local verifier rejection':'Return to fixed hosted experiment'}</button></div>}{record.source==='hosted'?<><p>Only the fixed lab identifier is sent to the runner.</p><button disabled={busy} onClick={()=>run()}>{busy?'Observation in progress…':'Run fixed experiment'}</button></>:<><p>{lab.id==='07'?'From the cloned repository root in the disposable Linux VM, run the intentionally broken object. Preserve the complete verifier diagnostic and kernel context. This is a rejection exercise, not a hosted run.':'Run the observer and fixture in separate terminals in the disposable Linux VM.'}</p><h3>Observer</h3><pre>{lab.id==='07'?'sudo INCIDENT_VERIFIER_BROKEN=1 ./scripts/run-lab.sh 07-verifier-portability --duration 5':detail.observer}</pre>{lab.id!=='07'&&<><h3>Fixture</h3><pre>{detail.fixture}</pre></>}<p>{detail.exercise}</p><p>{detail.cleanup}</p><label className="learn-field">Paste local output (user-provided, unverified)<textarea value={local} onChange={e=>setLocal(e.target.value)}/></label><button disabled={!local.trim()} onClick={()=>{update(r=>({...r,events:[...r.events,...local.split('\n').filter(s=>s.trim()).map((data,i)=>({sequence:(r.events.at(-1)?.sequence??0)+i+1,kind:lab.id==='07'?'diagnostic':'observation',timestamp:Date.now()/1000,data}))],runState:'local-unverified'}));setLocal('');}}>Append unverified output</button></>}
    <p role="status">Run status: {record.runState}{record.source==='local'?' · source is not verified by this application':''}</p>{error&&<p role="alert">{error}</p>}
    <EvidenceDiagram labId={lab.id} events={record.events} selectedSequence={selected} onSelect={setSelected}/>
    <div className="learn-evidence" aria-label="Raw evidence">{record.events.map(e=><article id={`evidence-${lab.id}-${e.sequence}`} key={e.sequence} className={selected===e.sequence?'learn-event selected':'learn-event'}><button onClick={()=>setSelected(e.sequence)}>Inspect #{e.sequence} · {e.kind}</button><pre>{e.data}</pre>{['observation','diagnostic'].includes(e.kind)&&<label><input type="checkbox" checked={record.citations.includes(e.sequence)} onChange={()=>update(r=>({...r,citations:r.citations.includes(e.sequence)?r.citations.filter(s=>s!==e.sequence):[...r.citations,e.sequence]}))}/>Cite this record</label>}</article>)}</div>
    <button disabled={!evidence.length||busy||!record.citations.length} onClick={()=>attempt('evidence',{events:record.events,citations:record.citations,runState:record.runState,sessionId:record.sessionId},'explain')}>Interpret selected evidence</button><p>Partial diagnostics may be interpreted as partial diagnostics. They do not establish successful execution.</p></div>}
    {record.phase==='explain'&&<div className="learn-panel"><p className="learn-kicker">Explain · argue from evidence</p><h2>Build a bounded explanation</h2><p>Citations: {record.citations.map(s=><a key={s} href={`#explanation-evidence-${s}`}> #{s} </a>)}</p><section aria-label="Cited raw evidence"><h3>Cited raw evidence</h3>{record.events.filter(e=>record.citations.includes(e.sequence)).map(e=><pre key={e.sequence} id={`explanation-evidence-${e.sequence}`}>#{e.sequence} {e.data}</pre>)}</section>{field('claim','Claim — what happened, within the evidence boundary?')}{field('mechanism','Mechanism — why does this hook and correlation support your claim?')}{field('unknown','Unknown — which alternative remains possible and why?')}{field('nextStep','Next experiment — what would you measure and how would each outcome change your view?')}<p>Presence checks below measure completeness only. They do not judge whether your explanation is correct.</p><button disabled={!explanationComplete(record)} onClick={()=>attempt('explanation',{...record.reasoning,citations:record.citations},'transfer')}>Preserve explanation and try transfer</button><button onClick={()=>update(r=>({...r,phase:'observe'}))}>Revise evidence selection</button></div>}
    {record.phase==='transfer'&&<div className="learn-panel"><p className="learn-kicker">Transfer · {record.transfer.assisted?'assisted':'no in-app help recorded'}</p><h2>Apply the idea in an unfamiliar situation</h2><p>{lab.id==='02'&&scenarios.includes('fallback')?'Changed runtime problem: the primary override configuration is missing, then a default configuration opens. Use the received pathname and return records to distinguish fallback behavior from total configuration failure. What intent remains unknown?':c.transfer}</p><p>Write before requesting help. Opening guidance or requesting the tutor marks this transfer as assisted.</p>{lab.id==='02'&&(scenarios.includes('fallback')?<><button disabled={busy} onClick={()=>run('fallback')}>Run changed fallback scenario</button><p>Transfer status: {record.transferRunState??'idle'} · session {record.transferSessionId??'not started'}</p>{record.transferEvents?.map(e=><pre key={e.sequence}>Transfer #{e.sequence} {e.data}</pre>)}</>:<p>Changed runtime scenario is unavailable on this runner. This is a written transfer exercise; no changed scenario execution is claimed.</p>)}{error&&<p role="alert">{error}</p>}<label className="learn-field">Your transfer reasoning<textarea value={record.transfer.answer} onChange={e=>update(r=>({...r,transfer:{...r.transfer,answer:e.target.value}}))}/></label><label><input type="checkbox" checked={!!record.transfer.outsideHelp} onChange={e=>update(r=>({...r,transfer:{...r.transfer,outsideHelp:e.target.checked}}))}/>I used outside help or reopened other notes for this transfer.</label><button disabled={!record.transfer.answer.trim()||busy} onClick={()=>{const at=new Date().toISOString();update(r=>({...r,phase:'review',transfer:{...r.transfer,submittedAt:at},reviewDueAt:r.reviewDueAt??new Date(Date.now()+604800000).toISOString(),attempts:[...r.attempts,{stage:'transfer',at,value:r.transfer.answer,assisted:r.transfer.assisted||!!r.transfer.outsideHelp}]}));}}>Preserve transfer for review</button></div>}
    {record.phase==='review'&&<div className="learn-panel"><p className="learn-kicker">Review · no automatic mastery claim</p><h2>Your explanation is ready for review</h2><p>{record.transfer.assisted||record.transfer.outsideHelp?'Help recorded for':'No in-app help recorded for'} transfer recorded. Compare the actual reasoning with each rubric dimension; finishing fields is not evidence of correctness.</p><div className="learn-rubric">{rubric.map(row=><article key={row.dimension}><h3>{row.dimension}</h3><p>{row.criterion}</p></article>)}</div><h3>Delayed recall</h3><p>Return after {record.reviewDueAt?new Date(record.reviewDueAt).toLocaleString():'seven days'} and answer before reopening guidance.</p><p>{lab.id==='02'&&scenarios.includes('relative')?'From memory first: the same relative pathname is opened after changing to two working directories; one succeeds and one fails. What context is missing from pathname-plus-return records, and how would you resolve the targets?':c.recall}</p>{lab.id==='02'&&scenarios.includes('relative')&&<><button disabled={busy} onClick={()=>run('relative')}>Run relative-path recall scenario</button><p>Recall status: {record.recallRunState??'idle'} · session {record.recallSessionId??'not started'}</p>{record.recallEvents?.map(e=><pre key={e.sequence}>Recall #{e.sequence} {e.data}</pre>)}</>}<label className="learn-field">Recall from memory<textarea value={record.recall.answer} onChange={e=>update(r=>({...r,recall:{...r.recall,answer:e.target.value}}))}/></label><label><input type="checkbox" checked={!!record.recall.outsideHelp} onChange={e=>update(r=>({...r,recall:{...r.recall,outsideHelp:e.target.checked}}))}/>I used outside help or reopened other notes for this recall.</label><button disabled={!record.recall.answer.trim()||busy} onClick={()=>{const at=new Date().toISOString();update(r=>({...r,recall:{...r.recall,submittedAt:at},attempts:[...r.attempts,{stage:'recall',at,value:{answer:r.recall.answer,dueAt:r.reviewDueAt,early:!!r.reviewDueAt&&Date.now()<Date.parse(r.reviewDueAt)},assisted:!!r.recall.assisted||!!r.recall.outsideHelp}]}));}}>Record recall attempt</button>{record.recall.submittedAt&&<p role="status">Recall recorded at {new Date(record.recall.submittedAt).toLocaleString()}. Timing is preserved; an early attempt is not delayed-recall evidence.</p>}<button onClick={()=>update(r=>({...r,phase:'explain'}))}>Revise explanation (earlier attempts retained)</button></div>}
    <aside className="learn-guidance"><h3>Authored guidance</h3><button onClick={hint}>Reveal next targeted hint{record.phase==='transfer'?' · marks transfer assisted':''}</button>{record.hints.filter(h=>record.phase!=='transfer'||h.phase==='transfer').filter(h=>record.phase!=='review'||h.phase==='review').map((h,i)=><p key={i}><strong>Hint {h.index+1} · {h.phase}:</strong> {c.hints[h.index]}</p>)}<details key={record.phase} onToggle={e=>{if(e.currentTarget.open)assistance('concept reference');}}><summary>Concept reference {record.phase==='transfer'?'(counts as assistance)':''}</summary>{c.concepts.map(concept=><article key={concept.title}><h4>{concept.title}</h4><p>{concept.description}</p></article>)}</details></aside>
    <details className="learn-tutor" key={record.phase} onToggle={e=>{if(e.currentTarget.open)assistance('tutor preview reference');}}><summary>Optional tutor critique</summary><p>The tutor sends the previewed material to Groq’s Qwen 3.8 27B model through this application. It is fallible and does not assign mastery. Groq may retain or process data under its applicable policies. Authored hints remain available if it is unconfigured. Your claim, mechanism, unknown, next experiment and hint count are sent only after consent and clicking Request.</p><p>Exact learner request preview (the server also includes this lab’s authored curriculum and rubric):</p><pre aria-label="Tutor request preview">{JSON.stringify(tutorPayload,null,2)}</pre><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I consent to send this written reasoning to the tutor service.</label><label><input type="checkbox" checked={includeEvidence} onChange={e=>setIncludeEvidence(e.target.checked)}/>Also send selected raw evidence (off by default).</label><button disabled={!consent||tutorBusy} onClick={requestTutor}>{tutorBusy?'Requesting critique…':'Request tutor critique'}</button>{tutor&&tutorPhase===record.phase&&<p role="status">{tutor}</p>}</details>
    <footer className="learn-footer"><button onClick={()=>downloadLearningRecord(record)}>Export complete learning record</button><details key={record.phase} onToggle={e=>{if(e.currentTarget.open)assistance('attempt history reference');}}><summary>Attempt and revision history ({record.attempts.length})</summary>{record.attempts.map((a,i)=><article key={i}><h4>{i+1}. {a.stage} · {a.assisted?'help recorded':'no in-app help recorded'} · {a.at}</h4><pre>{JSON.stringify(a.value,null,2)}</pre></article>)}</details></footer>
  </section>;
}
