import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { InvestigationFlow } from './InvestigationFlow';
import { labs } from '@/lib/labs';
import { newLearningRecord, readLearningRecord, saveLearningRecord } from '@/lib/learning';
vi.mock('./EvidenceDiagram',()=>({EvidenceDiagram:()=> <div>Evidence diagram</div>}));
class Stream { static instances:Stream[]=[]; listeners:Record<string,(e:MessageEvent)=>void>={}; onerror: (()=>void)|null=null;close=vi.fn();constructor(){Stream.instances.push(this);}addEventListener(name:string,cb:(e:MessageEvent)=>void){this.listeners[name]=cb;}emit(kind:string,data:string){this.listeners[kind]?.({data} as MessageEvent);}}
beforeEach(()=>{localStorage.clear();Stream.instances=[];vi.stubGlobal('EventSource',Stream);vi.stubGlobal('fetch',vi.fn());});
it('requires a correct readiness response and preserves wrong attempts',()=>{render(<InvestigationFlow lab={labs[0]}/>);fireEvent.click(screen.getByLabelText('The new executable completed successfully'));fireEvent.click(screen.getByText('Check readiness'));expect(screen.queryByText('Build a prediction')).toBeNull();fireEvent.click(screen.getByLabelText('An exec attempt reached the hook'));fireEvent.click(screen.getByText('Check readiness'));fireEvent.click(screen.getByText('Build a prediction'));expect(readLearningRecord('01')?.attempts).toHaveLength(2);expect(screen.getByText('Three competing hypotheses')).toBeTruthy();});
it('keeps partial diagnostics without accepting a completed substring',async()=>{const n=newLearningRecord('01');n.phase='observe';saveLearningRecord(n);vi.mocked(fetch).mockResolvedValueOnce({ok:true,json:async()=>({id:'abc',status:'queued'})} as Response).mockResolvedValueOnce({ok:true,json:async()=>({status:'failed'})} as Response);render(<InvestigationFlow lab={labs[0]}/>);fireEvent.click(screen.getByText('Run fixed experiment'));await waitFor(()=>expect(Stream.instances).toHaveLength(1));await act(async()=>{Stream.instances[0].emit('terminal',JSON.stringify({sequence:1,kind:'terminal',timestamp:1,data:'not completed'}));});await waitFor(()=>expect(readLearningRecord('01')?.runState).toBe('failed'));expect(readLearningRecord('01')?.events).toHaveLength(1);});
it('ignores malformed stream payloads and callbacks from a replaced run',async()=>{const n=newLearningRecord('01');n.phase='observe';saveLearningRecord(n);vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({id:'abc',status:'queued'})} as Response);render(<InvestigationFlow lab={labs[0]}/>);fireEvent.click(screen.getByText('Run fixed experiment'));await waitFor(()=>expect(Stream.instances).toHaveLength(1));act(()=>{Stream.instances[0].emit('observation','oops');Stream.instances[0].onerror?.();});fireEvent.click(screen.getByText('Run fixed experiment'));await waitFor(()=>expect(Stream.instances).toHaveLength(2));act(()=>Stream.instances[0].emit('observation',JSON.stringify({sequence:9,kind:'observation',timestamp:1,data:'stale'})));expect(readLearningRecord('01')?.events).toHaveLength(0);});
it('requires tutor consent and excludes raw evidence by default',async()=>{const n=newLearningRecord('01');n.events=[{sequence:1,kind:'observation',timestamp:1,data:'private raw'}];n.citations=[1];saveLearningRecord(n);vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({feedback:'Check the boundary'})} as Response);render(<InvestigationFlow lab={labs[0]}/>);expect(screen.getByText('Request tutor critique')).toBeDisabled();fireEvent.click(screen.getByLabelText('I consent to send this written reasoning to the tutor service.'));fireEvent.click(screen.getByText('Request tutor critique'));await waitFor(()=>expect(fetch).toHaveBeenCalled());const request=vi.mocked(fetch).mock.calls[0][1]!;expect(JSON.parse(request.body as string).evidence).toEqual([]);});
it('marks transfer assisted after authored help and retains the original submission',()=>{const n=newLearningRecord('01');n.phase='transfer';n.transfer.answer='My prediction';saveLearningRecord(n);render(<InvestigationFlow lab={labs[0]}/>);fireEvent.click(screen.getByText('Reveal next targeted hint · marks transfer assisted'));expect(readLearningRecord('01')?.transfer.assisted).toBe(true);fireEvent.click(screen.getByText('Preserve transfer for review'));expect(readLearningRecord('01')?.attempts.at(-1)?.assisted).toBe(true);expect(readLearningRecord('01')?.reviewDueAt).toBeTruthy();});
it('preserves a prior run automatically before retry',async()=>{const n=newLearningRecord('01');n.phase='observe';n.sessionId='first';n.runState='failed';n.events=[{sequence:1,kind:'diagnostic',timestamp:1,data:'first run diagnostic'}];saveLearningRecord(n);vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({id:'second',status:'queued'})} as Response);render(<InvestigationFlow lab={labs[0]}/>);fireEvent.click(screen.getByText('Run fixed experiment'));await waitFor(()=>expect(readLearningRecord('01')?.sessionId).toBe('second'));const receipt=readLearningRecord('01')?.runHistory?.[0];expect(receipt?.sessionId).toBe('first');expect(receipt?.events[0].data).toBe('first run diagnostic');});
it('retains independent training and transfer receipts',async()=>{const n=newLearningRecord('02');n.phase='transfer';n.sessionId='training';n.runState='completed';n.events=[{sequence:1,kind:'observation',timestamp:1,data:'training raw'}];saveLearningRecord(n);vi.mocked(fetch).mockImplementation(async(input)=>String(input).includes('capabilities')?{ok:true,json:async()=>({fileScenarios:['fallback']})} as Response:String(input).endsWith('/sessions')?{ok:true,json:async()=>({id:'transfer',status:'queued'})} as Response:{ok:true,json:async()=>({status:'completed'})} as Response);render(<InvestigationFlow lab={labs[1]}/>);await waitFor(()=>expect(screen.getByText('Run changed fallback scenario')).toBeTruthy());fireEvent.click(screen.getByText('Run changed fallback scenario'));await waitFor(()=>expect(Stream.instances).toHaveLength(1));await act(async()=>{Stream.instances[0].emit('terminal',JSON.stringify({sequence:1,kind:'terminal',timestamp:2,data:'done'}));});await waitFor(()=>expect(readLearningRecord('02')?.transferRunState).toBe('completed'));expect(readLearningRecord('02')?.sessionId).toBe('training');expect(readLearningRecord('02')?.transferSessionId).toBe('transfer');expect(readLearningRecord('02')?.events[0].data).toBe('training raw');});
it('outside help is recorded in transfer and recall attempts',()=>{const n=newLearningRecord('01');n.phase='transfer';n.transfer.answer='A test';saveLearningRecord(n);render(<InvestigationFlow lab={labs[0]}/>);fireEvent.click(screen.getByLabelText('I used outside help or reopened other notes for this transfer.'));fireEvent.click(screen.getByText('Preserve transfer for review'));expect(readLearningRecord('01')?.attempts.at(-1)?.assisted).toBe(true);fireEvent.change(screen.getByLabelText('Recall from memory'),{target:{value:'Recall test'}});fireEvent.click(screen.getByLabelText('I used outside help or reopened other notes for this recall.'));fireEvent.click(screen.getByText('Record recall attempt'));expect(readLearningRecord('01')?.attempts.at(-1)?.assisted).toBe(true);});
it('local verifier diagnostics never inherit hosted provenance',()=>{const n=newLearningRecord('07');n.phase='observe';n.sessionId='hosted';n.runState='completed';n.events=[{sequence:1,kind:'observation',timestamp:1,data:'hosted success'}];saveLearningRecord(n);render(<InvestigationFlow lab={labs[6]}/>);fireEvent.click(screen.getByText('Investigate local verifier rejection'));fireEvent.change(screen.getByLabelText('Paste local output (user-provided, unverified)'),{target:{value:'verifier rejected'}});fireEvent.click(screen.getByText('Append unverified output'));const saved=readLearningRecord('07')!;expect(saved.source).toBe('local');expect(saved.sessionId).toBeUndefined();expect(saved.events[0].kind).toBe('diagnostic');expect(saved.runHistory?.[0].sessionId).toBe('hosted');});
