"use client";
import { useState } from "react";
import Link from "next/link";
import { labs } from "@/lib/labs";
import { useLearningRecords, downloadLearningRecord, deleteLearningRecord, learningStatus, type LearningRecord } from "@/lib/learning";
import { rubric } from "@/lib/curriculum";
import { PageShell } from "./AppShell";
import { ReasoningReview } from "./ReasoningReview";
function Notebook({record}:{record:LearningRecord}) {
  const lab = labs.find(l=>l.id===record.labId)!;
  const [confirm,setConfirm] = useState(false);
  const [error,setError] = useState("");
  return <article className="review-card"><div className="review-meta"><span>CASE {record.labId} / {learningStatus(record)}</span><time>{new Date(record.updatedAt).toLocaleDateString()}</time></div><h2>{lab.shortTitle}</h2><p>{record.reasoning.claim || record.prediction.evidence || "Start with the readiness check. Your earlier work is preserved below."}</p><p className="note-provenance">{record.source === "local" ? "USER-PROVIDED OUTPUT · NOT INDEPENDENTLY VERIFIED" : record.runState === "completed" ? "HOSTED SESSION COMPLETED · HISTORICAL RECORD" : `HOSTED EXECUTION: ${record.runState.toUpperCase()}`}</p><details><summary>Read the investigation record</summary><h3>Original prediction</h3><p>{record.prediction.evidence || "No new prediction yet."}</p><h3>Selected evidence</h3>{record.events.filter(e=>record.citations.includes(e.sequence)).map(e=><pre key={e.sequence}>#{e.sequence} [{e.kind}] {e.data}</pre>)}<h3>Reasoning</h3>{Object.entries(record.reasoning).map(([key,value])=><div key={key}><strong>{key}</strong><p>{value || "Not recorded"}</p></div>)}<h3>Transfer</h3><p>{record.transfer.answer || "Not recorded"}</p><h3>Recall</h3><p>{record.recall.answer || "Not recorded"}</p><h3>Assistance and revisions</h3><p>{record.hints.length} authored hints. {record.attempts.length} preserved attempts and revisions. Export retains the full history.</p>{record.attempts.map((attempt,i)=><details key={i}><summary>{attempt.stage} · {attempt.assisted ? "assisted" : "no in-app help recorded"} · {new Date(attempt.at).toLocaleString()}</summary><pre>{JSON.stringify(attempt.value,null,2)}</pre></details>)}{record.legacy!==undefined&&<details><summary>Original legacy notebook</summary><pre>{JSON.stringify(record.legacy,null,2)}</pre></details>}</details><ReasoningReview record={record}/><div className="review-actions"><Link href={`/labs/${record.labId}`}>Continue case ↗</Link><button onClick={()=>downloadLearningRecord(record)}>Export private record ↓</button><button onClick={()=>setConfirm(true)}>Delete from this browser</button></div>{confirm&&<div className="delete-confirm"><p>Delete this notebook and its preserved legacy copy from this browser? Export first if you need a copy.</p><button onClick={()=>{if(!deleteLearningRecord(record.labId))setError("Could not delete the record. Browser storage may be blocked.");setConfirm(false);}}>Delete notebook</button><button onClick={()=>setConfirm(false)}>Keep notebook</button></div>}{error&&<p role="alert">{error}</p>}</article>;
}
export function NotebookCollection() {
  const records=useLearningRecords(); const all=Object.values(records).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  return <PageShell><div className="case-eyebrow">YOUR INVESTIGATION RECORDS<span>{all.length} CASES</span></div><div className="document-title"><h1>Keep the reasoning.<br/><em>Not just the result.</em></h1><p>First attempts, evidence, revisions, and the help you used. Stored on this device. Exported records may contain raw observations—keep them private.</p></div>{all.length?all.map(record=><Notebook key={record.labId} record={record}/>):<div className="empty-notebooks"><h2>Your first case starts with a question.</h2><p>Open a lab to begin a private notebook.</p><Link className="button primary" href="/labs/02">Investigate file access ↗</Link></div>}<details className="review-card"><summary>How an instructor should review these records</summary><p>Review the unassisted answer before viewing hints or revisions. Use the rubric below; record an evidence-based judgment outside the public repository. A learner’s self-review is not an independent assessment.</p>{rubric.map(r=><div key={r.dimension}><h3>{r.dimension}</h3><p>{r.criterion}</p></div>)}<p>Rate each dimension 0 (missing or contradicted), 1 (partly supported), or 2 (supported and appropriately bounded). Record disagreement rather than silently averaging it away. No automatic mastery score is assigned.</p></details></PageShell>;
}
