"use client";
import { useState } from "react";
import Link from "next/link";
import { labs } from "@/lib/labs";
import { downloadNotebook, removeNotebook, useNotebooks } from "@/lib/notebooks";
import { PageShell } from "./AppShell";
import { LabIcon } from "./LabIcons";
export function NotebookCollection() {
  const notes = useNotebooks(); const [confirm, setConfirm] = useState<string>(); const [error, setError] = useState("");
  const entries = Object.values(notes).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt));
  function remove(id: string) { if (!removeNotebook(id)) setError("This browser could not delete the notebook. Try allowing local storage."); setConfirm(undefined); }
  return <PageShell><div className="page-eyebrow"><span className="accent-square"/>YOUR FIELDWORK<span>{entries.length} NOTEBOOKS</span></div><div className="document-title"><h1>Keep the evidence.<br/><em>Keep the questions.</em></h1><p>Your drafts and case notes, saved on this device. Raw output stays here unless you choose to download it.</p></div>{error && <p role="alert" className="error">{error}</p>}{entries.length === 0 ? <div className="empty-notebooks"><LabIcon name="book" size={42}/><h2>A fresh notebook.</h2><p>Begin an investigation to save your prediction, evidence and reasoning here.</p><Link className="button primary" href="/">Choose an investigation →</Link></div> : <div className="notebook-collection">{entries.map(note => { const lab = labs.find(item => item.id === note.labId)!; return <article className="saved-notebook" key={note.labId}><div className="saved-note-meta"><span>INCIDENT {lab.id} / {note.phase === "complete" ? "COMPLETE" : "DRAFT"}</span><time dateTime={note.updatedAt}>{new Date(note.updatedAt).toLocaleDateString()}</time></div><h2>{lab.shortTitle}</h2><p>{note.prediction || "No prediction written yet."}</p><span className="note-provenance">{note.source === "local" ? "USER-PROVIDED LOCAL OUTPUT" : "SAVED HOSTED RUNNER EVENTS"}</span><details className="lab-details"><summary>Read this notebook</summary><h3>Prediction</h3><p>{note.prediction || "Not written yet."}</p><h3>Evidence</h3><pre>{note.source === "local" ? note.localEvidence || "No output recorded." : note.events.map(event => `[${event.kind}] ${event.data}`).join("\n") || "No events received."}</pre><h3>Interpretation</h3><p>{note.explanation || "Not written yet."}</p></details><div className="saved-note-actions"><Link href={`/labs/${lab.id}`}>Open notebook ↗</Link><button onClick={() => downloadNotebook(note)}>Download ↓</button><button onClick={() => setConfirm(note.labId)} aria-label={`Delete ${lab.shortTitle} notebook`}>Delete</button></div>{confirm === note.labId && <div className="delete-confirm"><p>Delete these saved notes and output from this browser?</p><button onClick={() => remove(note.labId)}>Delete notebook</button><button onClick={() => setConfirm(undefined)}>Keep notes</button></div>}</article>; })}</div>}<p className="notebooks-boundary">Completing a notebook records your learning progress. It does not certify a deployment, machine or environment.</p></PageShell>;
}
