"use client";
import Link from "next/link";
import { useLearningRecords } from "@/lib/learning";
import { curricula } from "@/lib/curriculum";
import { labs } from "@/lib/labs";
import { PageShell } from "./AppShell";
export function PracticeCollection(){
  const records=useLearningRecords();
  const reviews=Object.values(records).filter(r=>r.transfer.submittedAt).sort((a,b)=>(a.reviewDueAt??a.updatedAt).localeCompare(b.reviewDueAt??b.updatedAt));
  const weak=Object.values(records).flatMap(r=>{const review=r.attempts.filter(a=>a.stage==='rubric-review').at(-1)?.value as {scores?:number[]}|undefined;return review&&Array.isArray(review.scores)&&review.scores.some(s=>s===0||s===1)?[{record:r,scores:review.scores}]:[];});
  return <PageShell><div className="case-eyebrow">RECALL / VARIED PRACTICE<span>BUILD INDEPENDENCE</span></div><div className="document-title"><h1>Make it yours.<br/><em>Then try it again.</em></h1><p>Revisit the reasoning after seven days. Explain a changed case before reopening your notes. An early attempt is practice; it is not evidence of delayed retention.</p></div><section><h2>Your recall queue</h2>{reviews.length?reviews.map(r=><article className="practice-card" key={r.labId}><div className="review-meta"><span>CASE {r.labId} / {r.recall.submittedAt ? "RECALL RECORDED" : "RECALL SCHEDULED"}</span><time dateTime={r.reviewDueAt}>{r.reviewDueAt?new Date(r.reviewDueAt).toLocaleDateString():"After transfer"}</time></div><h2>{labs.find(l=>l.id===r.labId)?.shortTitle}</h2><p>{curricula[r.labId].recall}</p><Link className="button primary" href={`/labs/${r.labId}`}>Open recall exercise ↗</Link></article>):<article className="practice-card"><h3>No recall scheduled yet.</h3><p>Record a transfer attempt in any investigation. Its recall exercise becomes available with a seven-day target.</p><Link href="/labs/02">Start the file-access case ↗</Link></article>}</section>{weak.length>0&&<section><h2>Revisit after review</h2>{weak.map(({record})=><article className="practice-card" key={record.labId}><h3>{labs.find(l=>l.id===record.labId)?.shortTitle}</h3><p>A local rubric review marked at least one dimension missing or partly supported. Revisit the reasoning and explain what changes.</p><Link href={`/labs/${record.labId}`}>Revise this case ↗</Link></article>)}</section>}<section><h2>Revisit a prerequisite</h2><p>These concept references support practice. Read them after an independent attempt if you want an honest record of what you knew without help.</p><div className="concept-grid">{labs.map(lab=><article className="concept-card" key={lab.id}><span className="eyebrow">CASE {lab.id}</span><h3>{lab.shortTitle}</h3><p>{curricula[lab.id].concepts.map(c=>c.title).join(" · ")}</p><Link href={`/guide#concept-${lab.id}`}>Review the concepts ↗</Link></article>)}</div></section></PageShell>;
}
