"use client";
import { useState } from "react";
import { rubric } from "@/lib/curriculum";
import { saveLearningRecord, type LearningRecord } from "@/lib/learning";
type Review = {at:string;role:string;scores:number[];notes:string;attemptCount:number};
export function ReasoningReview({record}:{record:LearningRecord}) {
 const [role,setRole]=useState('self');const [scores,setScores]=useState<number[]>(rubric.map(()=>-1));const [notes,setNotes]=useState('');const [message,setMessage]=useState('');
 const reviews=record.attempts.filter(a=>a.stage==='rubric-review');
 function save(){if(scores.some(s=>s<0)||!notes.trim())return;const at=new Date().toISOString();const value:Review={at,role,scores,notes,attemptCount:record.attempts.length};const ok=saveLearningRecord({...record,updatedAt:at,attempts:[...record.attempts,{stage:'rubric-review',at,assisted:true,value}]});setMessage(ok?'Review saved locally, linked to the current attempt history. Reviewer identity is self-reported.':'Could not save review. Export your work before leaving.');}
 return <details className="reasoning-review"><summary>Record a rubric review</summary><p>Review the preserved response, not the learner’s writing style. This is a local reviewer judgment, not an authenticated certification.</p><label>Review perspective<select value={role} onChange={e=>setRole(e.target.value)}><option value="self">Learner self-review</option><option value="instructor">Instructor review (self-reported)</option></select></label>{rubric.map((row,i)=><label key={row.dimension}>{row.dimension}<p>{row.criterion}</p><select value={scores[i]} onChange={e=>setScores(current=>current.map((s,j)=>i===j?Number(e.target.value):s))}><option value={-1}>Choose a judgment</option><option value={0}>0 · Missing or contradicted</option><option value={1}>1 · Partly supported</option><option value={2}>2 · Supported and bounded</option><option value={3}>Unscorable · insufficient evidence</option></select></label>)}<label>Evidence for this review and any disagreement<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Refer to the attempt and cited evidence. Explain each weak or uncertain dimension."/></label><button className="button primary" disabled={scores.some(s=>s<0)||!notes.trim()} onClick={save}>Save local review</button>{message&&<p role="status">{message}</p>}<p>{reviews.length} review{reviews.length===1?'':'s'} retained in the exported attempt history.</p></details>;
}
