import Link from "next/link";
import { PageShell } from "@/components/AppShell";
import { repositoryUrl as repo } from "@/lib/links";
import { CodeBlock } from "@/components/CodeBlock";
export const metadata = { title: "Field guide · Incident Lab" };
export default function Guide() {
  return <PageShell><div className="page-eyebrow"><span className="accent-square"/>THE FIELD GUIDE<span>READ / RUN / REASON</span></div><div className="document-title"><h1>Get closer.<br/><em>Stay precise.</em></h1><p>A practical companion for your time inside the machine.</p></div><nav className="guide-contents" aria-label="Guide sections"><a href="#method">01 / The method</a><a href="#local-vm">02 / Local VM</a><a href="#boundaries">03 / Evidence limits</a><a href="#troubleshooting">04 / Troubleshooting</a></nav>
    <section className="guide-section" id="method"><span className="section-index">01</span><div><h2>The investigation method</h2><p>Start with a symptom and a prediction. A hook is useful when it answers a specific question.</p><div className="method-steps">{[["Predict", "Write down the event and identity fields you expect before running the observer."],["Observe", "Collect the real output. Inspect timestamps, identity, return values and the capture window."],["Explain + bound", "State what the evidence establishes, then name what it cannot tell you."],["Transfer", "Change one condition. Check whether your reasoning still holds."]].map(([title,text],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div><p>The 3D scenes are conceptual teaching models. Selecting a layer exposes its meaning; it does not attach a probe or run a command.</p><Link className="text-link" href="/labs/01">Start with process execution →</Link></div></section>
    <section className="guide-section" id="local-vm"><span className="section-index">02</span><div><h2>Prepare the local learner VM</h2><p>Labs 03–06 run in a disposable Linux VM. This learner release supports a macOS host with Lima 2.0 or newer and the pinned Ubuntu 24.04 x86_64 guest. The commands below run in a local clone of this repository.</p><CodeBlock label="HOST / GET THE REPOSITORY" code={`git clone ${repo}.git\ncd ebpf-incident-lab`}/><p>Download the pinned v0.1.1 learner bundle and check it against the repository’s published checksums.</p><CodeBlock label="HOST / PREPARE THE LEARNER BUNDLE" code={'mkdir -p vm/artifacts\ncurl --fail --location \\\n  https://github.com/danielAsaboro/ebpf-incident-lab/releases/download/v0.1.1/incident-lab-x86_64.tar.zst \\\n  --output vm/artifacts/incident-lab-x86_64.tar.zst\n(\n  cd vm/artifacts\n  awk \'$2 == "incident-lab-x86_64.tar.zst"\' ../../release/SHA256SUMS | shasum -a 256 --check\n)'}/><CodeBlock label="HOST / START AND ENTER" code={'./scripts/lab-vm.sh start\n./scripts/lab-vm.sh doctor\n./scripts/lab-vm.sh shell'}/><p>Open a second host terminal and run the shell command again for the fixture. Inside the guest, observers run from native storage at /opt/incident-lab.</p><CodeBlock label="GUEST / CHECK THE ENVIRONMENT" code={'incident-lab doctor\nincident-lab list'}/><p>Each local investigation contains its own observer and fixture commands. Nothing in this web interface runs shell commands on your machine.</p><div className="guide-callout"><strong>Stop preserves the VM.</strong><p>After fieldwork, use <code>./scripts/lab-vm.sh stop</code> on the host. Reset and delete are separate destructive operations with explicit terminal confirmations.</p></div><a className="text-link" href={`${repo}/blob/main/vm/README.md`} target="_blank" rel="noreferrer">Full VM reference ↗</a></div></section>
    <section className="guide-section" id="boundaries"><span className="section-index">03</span><div><h2>Keep the evidence honest</h2><div className="boundary-table"><div><b>Hosted runner events</b><p>Received from the configured Linux runner. A successful run applies to that object, kernel and observation window.</p></div><div><b>Local output</b><p>Pasted by you and labeled user-provided. The application cannot independently verify its origin or execution.</p></div><div><b>Saved notebooks</b><p>Stored in this browser, including the output you record. They are historical notes, not a current live session. Delete individual notebooks from My notebooks.</p></div><div><b>Empty output</b><p>No matching event reached the observer. That does not establish that the incident never happened.</p></div><div><b>Conceptual models</b><p>Explain relationships. They are not actual process topology, physical kernel layouts, network measurements or verifier disassembly.</p></div></div></div></section>
    <section className="guide-section" id="troubleshooting"><span className="section-index">04</span><div><h2>Follow the visible error</h2>{[["The hosted runner is not configured", "This deployment has no configured runner credentials. The UI remains usable; use the local VM guides or a deployment with a configured runner."],["No events appeared", "Run the fixture after the observer reports ready. Check the capture duration and ensure --pid refers to a host PID."],["Learner bundle checksum mismatch", "Use the exact pinned archive and published checksum. The launcher will not silently download or rebuild a replacement."],["A saved stream was interrupted", "Returning to a notebook restores its notes and received events. It does not automatically restart a runner session. Return to your prediction to start another observation."],["The 3D scene is unavailable", "The textual layer controls, lab content and notebook remain usable without WebGL."],["Uprobe symbol or attach failure", "Use the fixture binary on the VM's native filesystem, not the macOS shared mount. Check the exact INCIDENT_DNS_FIXTURE path."]].map(([title,text])=><details className="guide-faq" key={title}><summary>{title}</summary><p>{text}</p></details>)}<a className="text-link" href={`${repo}/blob/main/docs/TROUBLESHOOTING.md`} target="_blank" rel="noreferrer">Complete troubleshooting reference ↗</a></div></section>
  </PageShell>;
}
